// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AnalistaEEstrategicoOPerfilDevNoMundoDasIasDocumentDataSlicesSlice = never;

/**
 * Content for Analista e estratégico: o perfil dev no mundo das IAs documents
 */
interface AnalistaEEstrategicoOPerfilDevNoMundoDasIasDocumentData {
  /**
   * Analista e estratégico field in *Analista e estratégico: o perfil dev no mundo das IAs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: title
   * - **API ID Path**: analista_e_estrategico_o_perfil_dev_no_mundo_das_ias.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * O Google anunciou field in *Analista e estratégico: o perfil dev no mundo das IAs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: analista_e_estrategico_o_perfil_dev_no_mundo_das_ias.o_google_anunciou
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  o_google_anunciou: prismic.RichTextField;

  /**
   * Slice Zone field in *Analista e estratégico: o perfil dev no mundo das IAs*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: analista_e_estrategico_o_perfil_dev_no_mundo_das_ias.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AnalistaEEstrategicoOPerfilDevNoMundoDasIasDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Analista e estratégico: o perfil dev no mundo das IAs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: analista_e_estrategico_o_perfil_dev_no_mundo_das_ias.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Analista e estratégico: o perfil dev no mundo das IAs*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: analista_e_estrategico_o_perfil_dev_no_mundo_das_ias.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Analista e estratégico: o perfil dev no mundo das IAs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: analista_e_estrategico_o_perfil_dev_no_mundo_das_ias.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Analista e estratégico: o perfil dev no mundo das IAs document from Prismic
 *
 * - **API ID**: `analista_e_estrategico_o_perfil_dev_no_mundo_das_ias`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AnalistaEEstrategicoOPerfilDevNoMundoDasIasDocument<
  Lang extends string = string
> = prismic.PrismicDocumentWithUID<
  Simplify<AnalistaEEstrategicoOPerfilDevNoMundoDasIasDocumentData>,
  "analista_e_estrategico_o_perfil_dev_no_mundo_das_ias",
  Lang
>;

export type AllDocumentTypes =
  AnalistaEEstrategicoOPerfilDevNoMundoDasIasDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AnalistaEEstrategicoOPerfilDevNoMundoDasIasDocument,
      AnalistaEEstrategicoOPerfilDevNoMundoDasIasDocumentData,
      AnalistaEEstrategicoOPerfilDevNoMundoDasIasDocumentDataSlicesSlice,
      AllDocumentTypes,
    };
  }
}
